## Splicing Strings

In [16]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


In [3]:
# printed value of element[:4], or letters up to 4th letter (including 4th letter)
print(element[:4])

oxyg


In [6]:
# printed value of element[4:], or letters after 4th letter (not including 4th letter)
print(element[4:])

en


In [7]:
# printed value of element[:], or all letters
print(element[:])

oxygen


In [8]:
# printed value of element[-1], or first letter from the end
print(element[-1])

n


In [9]:
# printed value of element[-2], or second letter from the end
print(element[-2])

e


In [12]:
# printed value of element[1:-1], or characters from second letter to the first letter from the end (not including the first letter from the end)
print(element[1:-1])

xyge


In [17]:
# printing strings from inflammation-01.csv
import numpy as np
medical_data = np.loadtxt("inflammation-01.csv",delimiter = ",")
print(medical_data[3:3,4:4])
print(medical_data[3:3,:])
#both produce empty strings

[]
[]


## Stacking Arrays

In [14]:
import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
# Sliced first and last column of A, stacked columns, and printed results
beg = np.vstack(A[:,0])
end = np.vstack(A[:,-1])
Stacked = np.hstack([beg, end])
print(Stacked)

[[1 3]
 [4 6]
 [7 9]]


In [27]:
npdiff = numpy.array([ 0,  2,  5,  9, 14])
numpy.diff(npdiff)

array([2, 3, 4, 5])

In [28]:
# 1. It would make sense if we worked along axis = 1 (rows) since that would show the change in inflammation over time for each patient.

In [29]:
# 2.
# If the shape of an individual data file is (60, 40) (60 rows and 40 columns), the shape of the array would be (60,39) after running the diff() function. 
# The diff() function tracks changes across each row and results in one less value for each row. 
# We do not lose any rows, but we do lose a column. 

In [30]:
# 3. Finding largest change in inflammation for each patient
# I found the change of each inflammation value compared to the previous value for each patient using np.diff()
# It matters if the change in inflammation is an increase or decrease since simply finding the max value of the previous dataset will exclude really large negative numbers.
# Thus, I find the absolute value of the np(diff) values and then find the max of it using np.max(np.abs(npdiff(medical_data)))
change_inf = np.max(np.abs(np.diff(medical_data)), axis = 1)
print(change_inf)

[12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.
 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.
 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.]
